let o = \s.\z.z in
let o' = \s.\z.sz in
let o'' = \s.\z.s(sz) in
let y = \t.\f.t in
let n = \t.\f.f in
let c = \l.\m.\n.lmn in
let p = \f.\s.\b.bfs in
let f = \p.py in
let s = \p.pn in
let a = \m.\n.\s.\z.ms(nsz) in
let z = \m.m(\x.n)y in
let z' = poo in
let s' = \x.p(sx)(ao'(sx)) in
let d = \m.f(ms'z') in
let g = \f.\n.c(zn)o(an(f(dn))) in
let f' = \f.(\x.f(\y.xxy))(\x.f(\y.xxy)) in
let u = f'g in
uo''
